### PR TITLE
Pull sitemaps from disk

### PR DESCRIPTION
**Pull request by medoror**
* Provide a directory of xml sitemaps on disk as an option to initializing SitemapToContentDatabase
* Allow for multiple sitemap urls

### CODE REVIEW

**Comment by medoror** [comment]
Addresses issue #8 . This branch also allows for multiple sitemaps to be used via the filesystem or urls in the old manner

**Comment by philippe2803** [comment]
Cool idea. 
Would you be able to add a unit test?

**Comment by medoror** [comment]
> Cool idea. 
> Would you be able to add a unit test?

yea I can

**Comment by medoror** [comment]
@philippe2803 Sorry was at a work event all week. I have properly implemented this feature with passing unit tests.  Let me know what you think

**Comment by philippe2803** [comment]
@medoror just saw your message only now. Not sure how I missed it. Sorry about this. Running the tests now. I will merge automatically when the tests are finished

**Comment by philippe2803** [comment]
@medoror thanks for your contribution very much. It really adds something valuable. A couple of things I noticed after merging the PR (completely my fault for not noticing) that you should know in case you want to contribute more:
 - I use semantic release, so it gets uploaded to pipy automatically as long as the commit message is in the form "feat: <commit message>  or fix:<commit message>". If this is not done, the release will not happen.
 - Unit tests should be made using Pytest.

You don't have to correct anything though, I made a a quick commit that follow the semantic release to trigger the release and it worked.

**Pull request merged**
